// Mocks generated by Mockito 5.2.0 from annotations
// in notr/test/services/authentication_service_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:notr/models/email_and_password_credentials.dart' as _i5;
import 'package:notr/repository/authentication_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUserCredential_0 extends _i1.Fake implements _i2.UserCredential {}

/// A class which mocks [AuthentiationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthentiationRepository extends _i1.Mock
    implements _i3.AuthentiationRepository {
  MockAuthentiationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserCredential> signInWithEmailAndPassword(
          _i5.EmailAndPasswordCredentials? credentials) =>
      (super.noSuchMethod(
              Invocation.method(#signInWithEmailAndPassword, [credentials]),
              returnValue:
                  Future<_i2.UserCredential>.value(_FakeUserCredential_0()))
          as _i4.Future<_i2.UserCredential>);
  @override
  _i4.Stream<_i2.User?> authStateChanges() =>
      (super.noSuchMethod(Invocation.method(#authStateChanges, []),
          returnValue: Stream<_i2.User?>.empty()) as _i4.Stream<_i2.User?>);
}

/// A class which mocks [UserCredential].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserCredential extends _i1.Mock implements _i2.UserCredential {
  MockUserCredential() {
    _i1.throwOnMissingStub(this);
  }
}
