// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3LF0ItZTVzMvHyXm9TWiLtnSlhJ-jn_E',
    appId: '1:5568802205:android:14aedc955df1b049549374',
    messagingSenderId: '5568802205',
    projectId: 'notr-dev',
    storageBucket: 'notr-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVtDpnuNR0YHyDH6QE-_WIoiZvlbKuwGk',
    appId: '1:5568802205:ios:375c519013366e01549374',
    messagingSenderId: '5568802205',
    projectId: 'notr-dev',
    storageBucket: 'notr-dev.appspot.com',
    iosClientId: '5568802205-gsqidnrj2s9nsrm442ogoneghkn1aj75.apps.googleusercontent.com',
    iosBundleId: 'com.simeon.notr',
  );
}
